innova_taxonomy:
    resource: "@InnovaTaxonomyBundle/Controller/"
    type:     annotation
    prefix:   /

innova_activity:
    resource: "@InnovaActivityBundle/Controller/"
    type:     annotation
    prefix:   /

innova_learningpath:
    resource: "@InnovaLearningPathBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"